# This dockerfile will build a CentOS 5 based linux rpm
FROM       centos:5.11
MAINTAINER B-Lex IT BV <info@b-lex.com>
ENV        RPMBASE=/usr/src/redhat
RUN        yum install -y gcc rpm-build make
RUN        cd /root/ &&
